# Generated by Django 4.2.4 on 2023-08-16 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('Description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('Description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('date_of_creation', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('modified_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата правки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товавры',
            },
        ),
    ]
