# Generated by Django 4.2.4 on 2023-08-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_description_category_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.CharField(max_length=150, verbose_name='slug')),
                ('content', models.TextField(verbose_name='Контент')),
                ('prevuew', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('date_create', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликованно')),
                ('views_count', models.IntegerField(default=0, verbose_name='Просмотры')),
            ],
        ),
    ]
